OAUTH_BODY_HASH = 'oauth_body_hash'
OAUTH_CONSUMER_KEY = 'oauth_consumer_key'
OAUTH_NONCE = 'oauth_nonce'
OAUTH_SIGNATURE = 'oauth_signature'
OAUTH_SIGNATURE_METHOD = 'oauth_signature_method'
OAUTH_TIMESTAMP = 'oauth_timestamp'
OAUTH_VERSION = 'oauth_version'