class TransferRequest(object):

    def __init__(self):
        self.local_date = ''
        self.local_time = ''
        self.transaction_reference = ''
        self.sender_name = ''
        self.sender_address = ''
        self.funding_card = ''
        self.funding_mapped = ''
        self.funding_ucaf = ''
        self.funding_mastercard_assigned_id = ''
        self.funding_amount = ''
        self.receiver_name = ''
        self.receiver_address = ''
        self.receiver_phone = ''
        self.receiving_card = ''
        self.receiving_amount = ''
        self.channel = ''
        self.ucaf_support = ''
        self.ica = ''
        self.processor_id = ''
        self.routing_and_transit_number = ''
        self.card_acceptor = ''
        self.transaction_desc = ''
        self.merchant_id = ''